Update ci-cd.yaml

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -7,44 +7,38 @@ on:
 
 jobs:
   Deploy:
-    name: Deploy to EC2
     runs-on: ubuntu-latest
     
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Set up SSH
-        uses: webfactory/ssh-agent@v0.5.3
-        with:
-          ssh-private-key: ${{ secrets.EC2_KEY }}
-
       - name: Deploy to EC2
+        uses: appleboy/ssh-action@master
         env:
+          ssh-private-key: ${{ secrets.EC2_KEY }}
           HOSTNAME: ${{ secrets.EC2_HOST }}
           USER_NAME: ${{ secrets.EC2_USER }}
-        run: |
-          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} << 'EOF'
-            # Navigate to your project directory
-            cd ~/my-project
+          sript: |
+            ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} << 'EOF'
+              # Navigate to your project directory
+              cd ~/my-project
             
-            # Install pm2 if not already installed
-            if ! command -v pm2 &> /dev/null
-            then
-              echo "pm2 not found, installing..."
-              sudo npm install -g pm2
-            else
-              echo "pm2 is already installed"
-            fi
+              # Install pm2 if not already installed
+              if ! command -v pm2 &> /dev/null
+              then
+                echo "pm2 not found, installing..."
+                sudo npm install -g pm2
+              else
+                echo "pm2 is already installed"
+              fi
 
-            # Pull the latest changes from the repository
-            git pull origin main
+              # Pull the latest changes from the repository
+              git pull origin main
 
-            # Install the necessary dependencies
-            yarn install
+              # Install the necessary dependencies
+              yarn install
 
-            # Build the Strapi application
-            yarn build
+              # Build the Strapi application
+              yarn build
 
-            # Restart the Strapi server using pm2
-            pm2 restart strapi-api || pm2 start npm --name strapi-api
-          EOF
+              # Restart the Strapi server using pm2
+              pm2 restart strapi-api || pm2 start npm --name strapi-api
+            EOF
